version: "3"
services:
  listings:
    build:
      dockerfile: "./listings-service/Dockerfile"
    environment:
      - MYSQL_HOST_URL=listings-db
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - listings-db
    volumes:
      - ./listings-service:/opt/app
      - /opt/app/node_modules

  listings-db:
    image: mysql:5.7.43
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 3003:3306

  users:
    build:
      dockerfile: "./users-service/Dockerfile"
    environment:
      - MYSQL_HOST_URL=users-db
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - users-db
    volumes:
      - ./users-service:/opt/app
      - /opt/app/node_modules

  users-db:
    image: mysql:5.7.43
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 3004:3306
